version: '3.2'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
  
  infra-wait:
    image: waisbrot/wait
    depends_on:
      - postgres
    environment:
      - TARGETS=postgres:5432

  load-script:
    build:
      context: ..
      dockerfile: Dockerfile.python
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_USER: postgres
      MARKETING_DB_NAME: marketing
      TOTAL_NUM_ADS: 22
      USER_DB_NAME: users
    volumes:
      - ../:/app
